x-base: &base
  command: /lab/_scripts/run.sh
  volumes:
    - .:/lab
  # network_mode: "service:tailscale"
  # depends_on:
  #   - tailscale
  stdin_open: true
  tty: true
  deploy:
    resources:
      reservations:
        devices:
          - capabilities: [gpu]
  env_file:
    - path: ./default.env
      required: true
    - path: ./.env
      required: false

services:
  4dgs-wu:
    <<: *base
    shm_size: 4gb
    build:
      context: ./4dgs-wu
      args:
        COLMAP_BRANCH: main
    working_dir: /lab/4dgs-wu

  4dgs-yang:
    <<: *base
    shm_size: 512mb
    build:
      context: ./4dgs-yang
      args:
        SRCDIR: 4dgs-yang
        COLMAP_BRANCH: main
        CUDA_IMAGE_TAG: "11.8.0-cudnn8-devel-ubuntu22.04"
    working_dir: /lab/4dgs-yang

  tailscale:
    build: ./_services/tailscale
    secrets:
      - tailscale
    environment:
      TAILSCALE_AUTH_KEY: "file:/run/secrets/tailscale"
      TAILSCALE_HOSTNAME: labll
      TAILSCALE_STATE_ARG: "mem:"

secrets:
  tailscale:
    file: .secrets/tailscale
