version: "3"

x-base: &base
  command: /lab/_scripts/run.sh
  tty: true
  stdin_open: true
  working_dir: /lab
  volumes:
    - .:/lab
  deploy:
    resources:
      reservations:
        devices:
          - capabilities: [gpu]

services:
  4dgs-wu:
    <<: *base
    build: ./4dgs-wu
    working_dir: /lab/4dgs-wu
    environment:
      WORKDIR: /lab/4dgs-wu
