version: "3"

x-base: &base
  command: /lab/_scripts/run.sh
  working_dir: /lab
  volumes:
    - .:/lab
  network_mode: "service:tailscale"
  depends_on:
    - tailscale
  deploy:
    resources:
      reservations:
        devices:
          - capabilities: [gpu]
  env_file:
    - path: ./default.env
      required: true
    - path: ./.env
      required: false

services:
  4dgs-wu:
    <<: *base
    shm_size: 4gb
    build:
      context: ./4dgs-wu
      args:
        COLMAP_BRANCH: main
  tailscale:
    build: ./_services/tailscale
    secrets:
      - tailscale
    environment:
      TAILSCALE_AUTH_KEY: "file:/run/secrets/tailscale"
      TAILSCALE_HOSTNAME: labll
      TAILSCALE_STATE_ARG: "mem:"

secrets:
  tailscale:
    file: .secrets/tailscale
