version: "3"

x-base: &base
  command: /lab/_scripts/run.sh
  tty: true
  stdin_open: true
  working_dir: /lab
  volumes:
    - .:/lab
  deploy:
    resources:
      reservations:
        devices:
          - capabilities: [gpu]
  env_file:
    - path: ./default.env
      required: true
    - path: ./.env
      required: false

services:
  4dgs-wu:
    <<: *base
    build:
      context: ./4dgs-wu
      args:
        COLMAP_BRANCH: main
